### ISSUE TITLE
Decide on format for the list items

### ISSUE THREAD

**Issue by ledell** [rladies/awesome-rladies-blogs#1]
I started with a very basic format which includes the name of the blog (linked to the actual blog) and then the author(s), with some link to a personal page (e.g. twitter or homepage).  

- [Piping Hot Data](https://www.pipinghotdata.com) by [Shannon Pileggi](https://twitter.com/PipingHotData)

The format can be enriched however we like; we just need to make sure all the list items follow the same formatting. When submitting to the Awesome List, they prefer that the list items come with descriptions, so we can consider adding some descriptions of the blogs to the list items.

**Comment by Athanasiamo** [comment]
I have been toying with an idea for something featuring the blogs of R-Ladies for the webpage, so this is really great!
For integration with the website, the most convenient format is a json, where every new entry is its own json. This way, adding a new entry means copying another entry, and substituting the content.

**Comment by apreshill** [comment]
👋 

Also shared with @shannonpileggi, but I recently made a simple clickable list for this website: https://pkgs.rstudio.com/

The page is a single distill article (so .Rmd) that reads in a file and makes a table with reactable. Can be fancied up with a GH workflow to deploy, json data structure, etc. In case it is useful, happy to share code, I was just looking for something lightweight that didn't need much in the way of care and feeding 🐹

**Comment by ledell** [comment]
@Athanasiamo Cool!  If you're going to use this data for the website, then yeah it makes sense to use JSON instead.  @apreshill shared this example which uses JSON: https://github.com/sellorm/awesome-blogdown

What if we use this repo to collect submissions in JSON, and then periodically we move over rladies.org website or even better, have it automated?  Or we could collect submissions directly in the website repo and close this repo?  We have options...

I don't have the bandwidth at the moment to figure out how to get the JSON converted into a website, but I am happy to review & merge PRs and help promote the idea.

**Comment by Athanasiamo** [comment]
I can do this, no problem. I already use collections of jsons for the directory, which is grabbed on build through a GH action, so this should be totally feasible :) 

Thank you for the example @apreshill ! I'm likely go with hugo data templates directly for this, since the website is being made in Hugo and I think it'll be great to have it integrated there :) 

I think, next to deciding on exactly how the jsons should look, I'll also need to create a json validation action on PR to this repo, so we can be 100% sure that the submitted jsons are as we want them.

**Comment by yabellini** [comment]
This is so nice! I love the blog list on twitter.  Maybe we can use the IWD2021 campaign as an excuse for collecting more data?.  My plans for this year include R-Ladies blogs (and packages and books or other R-Ladies products) but we can focus on blogs and help to gather and spread the data (please no joke about pivot :-P).  We always use that campaign to update our data. What do you think? Let me know how I can help.

**Comment by Athanasiamo** [comment]
ok, y'all! I've done some work and have a suggestion for a json format in the blogs folder. This format is also validated through a Github action :) I've also made a small suggestion to how it might look on the webpage:

![image](https://user-images.githubusercontent.com/14014329/108781735-a3cc7200-756a-11eb-926c-fe55d5cde783.png)

**Comment by shannonpileggi** [comment]
I think it looks great! would there be an option for a linkedin icon as well? the json bits are above my head, but i am happy to do manual data entry and / or spread the word so just let me know what i can do!  and great job making this move forward so quickly! 👏

**Comment by Athanasiamo** [comment]
I'll write some instructions on how to copy and edit the jsons, @shannonpileggi . I hope clear instructions will make it comfortable to do. 

There is already support for linkedIn icon. I'll make sure to add a list all the icons that are available.

**Comment by shannonpileggi** [comment]
Super, thanks!

One thing I also considered was how to frame this to be more inclusive of any R-Ladies creating online content, but not necessarily a blog.  For example, what if Jesse Mostipak had her own website and a lot of awesome YouTube videos, but not a blog component? Or Danielle Navarro who creates amazing online content but doesn't blog?

Any thoughts on if this awesome list should be restricted to blogging vs online #rstats content more generally?

**Comment by Athanasiamo** [comment]
These are very good thoughts @shannonpileggi ! Indeed, it would seem like a good idea to allow diverse types of content.

**Comment by shannonpileggi** [comment]
Maybe people could submit personal websites and self-tag with categories?  LIke blog, open source course materials, video tutorials, workshops, presentations...  I don't want to make it too complicated, though.

**Comment by Athanasiamo** [comment]
Ok. For now we will stick to only blogs, and we can continue discussion on what and how to add other types of content in #5 . 

There is a [CONTRIBUTING](https://github.com/rladies/awesome-rladies-blogs/blob/main/CONTRIBUTE.md) on how to add new items, that I hope will be sufficient to start with. 

I have json validation workflows running on all PRs, so we should get good ideas of json states before merging.

**Comment by Athanasiamo** [comment]
I think this is such an excellent resource, thank you @shannonpileggi for getting us working on this :) 

EIther way is good I think :) I guess DM'ing bloggers and asking them is a good way also to ask permission to list their blog on the page.

**Comment by yabellini** [comment]
Hi, I jump here to say that I agree with the DM (people will respond in higer rates) and after that (and we have some more entries) I think is a good idea also do open call so we give an opportunity to add their blog to everybody not only the people we know they have blogs.

What do you think?
 
This is so great! Thanks for working on this.

**Comment by Athanasiamo** [comment]
I think DM those we know directly is great, @shannonpileggi amassed such a great list when she tweeted about it!

but we absolutely want a general call, @yabellini !  We want the hugest list! :) 
 Before we do, I just had the idea to enrich the json with language tag, so that it is easier to in the future be able to use this tag for sorting etc (I have not implented any sorting etc on the website, but it should be something to figure out at some point).

**Comment by Athanasiamo** [comment]
I'm going to close this issue now, as I think we have a great start now. I will open a new issue to remember to look at how we might integrate other types of content too, not just blogs.
