### ISSUE TITLE
Add blogs also as tiles with image and name of author

### ISSUE THREAD

**Issue by cosimameyer** [rladies/awesome-rladies-blogs#62]
I played a bit around yesterday and created the blogs also as a [tiles/grid representation](https://github.com/cosimameyer/awesome-pyladies-blogs#list-of-blogs-as-tiles)to have them both as a list and as a tile representation. It's implemented in the PyLadies' repository and not perfect yet but if you'd also want this for the Awesome R-Ladies' repository, I could add the code parts.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/7782895/233831682-3e324554-bd9b-4b5f-8773-25f425e837a9.png">

**Comment by drmowinckels** [comment]
How cool! :) 

The list feeds to our webpage, so I'm not sure its necessary with a grid view as well in our case. I might be wrong though!

But we should _for sure_ add link to the website page with the list. And also to the bot on mastodon.

**Comment by cosimameyer** [comment]
That absolutely makes sense 😊 I added it to have a visual effect and to better showcase the contributors - exactly what you did with the website. I just didn't think of it 😄 
And thanks so much for adding the website and the bot - that's fantastic! ✨
