### ISSUE TITLE
[New Blog]: 

### ISSUE THREAD

**Issue by lgibson7** [rladies/awesome-rladies-blogs#65]
### Blog Name

Once Upon a Time Series

### Blog URL

https://lgibson7.quarto.pub/once-upon-a-time-series/

### Author Name

Lydia Gibson

### Author Twitter Username

Lydz_is_Poppin

### Author GitHub Username

lgibson7

### Code of Conduct

- [X] I agree to follow R-Ladies' Code of Conduct

**Comment by drmowinckels** [comment]
Thank you for wanting to add you blog! 

@cosimameyer, can I ask you for help in structuring a new file for this, and following up with @lgibson7 about possible extra information to add?

**Comment by cosimameyer** [comment]
Thanks so much for contributing, @lgibson7! 🥳 

I'd love to help more but I'm about to board a plane and don't have my computer with me 🙃 

This is the info that we need (it's the info provided by Lydia + the photo URL):

```
{
  "title": "Once Upon a Time Series",
  "type": "blog",
  "url": "https://lgibson7.quarto.pub/once-upon-a-time-series/",
  "photo_url": "https://lgibson7.quarto.pub/once-upon-a-time-series/profile_pic.jpeg",
  "language": "en",
  "rss_feed": "[url]/file.xml", //required
  "authors": [
    {
      "name": "Lydia Gibson",
      "social_media": [{
         "twitter": "Lydz_is_Poppin",
         "github": "lgibson7"
      }]
    }
  ]
}
```

I couldn't identify an RSS feed on  the website - did you set one up, @lgibson7? As far as I understand the website is Quarto based - probably [this guide helps](https://github.com/rladies/awesome-rladies-blogs/blob/main/CONTRIBUTING.md#rss-feed)? 😊

**Comment by lgibson7** [comment]
Hello @cosimameyer. I've just added an [RSS feed](https://lgibson7.quarto.pub/once-upon-a-time-series/index.xml) to my blog site.

**Comment by cosimameyer** [comment]
@lgibson7 thank you so much ☺️ From what I can see, it looks good to me! I'll set up the PR 🥳

**Comment by lgibson7** [comment]
Awesome! Thanks @cosimameyer!
