### ISSUE TITLE
A recent entry is making the website build fail.

### ISSUE THREAD

**Issue by drmowinckels** [rladies/awesome-rladies-blogs#86]
It looks like the image it is trying to retrieve is not at the url specified.

https://github.com/rladies/rladies.github.io/actions/runs/7392280717/job/20110507817#step:15:30

**Comment by cosimameyer** [comment]
I looked into it - I merged [Jadey's](https://github.com/rladies/awesome-rladies-blogs/blob/main/blogs/jadeyryan.com.json) entry earlier - but the [image](https://jadeyryan.com/assets/img/JR-logo.webp) looks good to me. Does it have to be a PNG/JPG?

**Comment by drmowinckels** [comment]
Hugo docs imply that webp should work.

https://gohugo.io/content-management/image-processing/#quality

I'm not entirely sure what is going on here...

**Comment by drmowinckels** [comment]
I have to conclude that while hugo can deal with webp images from remote (but will work with webp images inside the repo). 

@jadeynryan any chance your website has a jpg/png version of that image somewhere?

**Comment by jadeynryan** [comment]
Sorry for the trouble! I just added a png to my website repo. Please let me know if you need anything else from me.

https://github.com/jadeynryan/jadey_website/blob/d7bb1feecd688eba63bd2bfe6af3e8e176c55cd4/assets/img/JR-logo.png

**Comment by drmowinckels** [comment]
absolutely no need to apologise, this was unexpected for all of us. I've updated the entry in [21f3ede](https://github.com/rladies/awesome-rladies-blogs/commit/21f3ede0b4a73cb673e7929a8e8fc0457bb7e88f) and that seems to have fixed the website build.

Thank you for responding so past @jadeynryan !
